#!/usr/bin/env python3
"""
agent_orchestrator.py — Master orchestration script for P1 sub-agents.

Run this to execute all data collection tasks in sequence.
Each agent logs its status. Failed tasks are logged to ISSUES.md.

Usage: python sub_agents/agent_orchestrator.py
"""

import subprocess
import sys
import os
from datetime import datetime

AGENT_PIPELINE = [
    ("P1-DA-01", "DataAgent_ADB",   "sub_agents/DataAgent_ADB.py"),
    ("P1-DA-03", "DataAgent_SEBI",  "sub_agents/DataAgent_SEBI.py"),
    ("P1-LIT-01", "LitAgent_P1",   "sub_agents/LitAgent_P1.py"),
]

ISSUES_FILE = "ISSUES.md"

def log_issue(task_id: str, agent: str, error: str):
    with open(ISSUES_FILE, 'a') as f:
        f.write(f"\n## {datetime.now().strftime('%Y-%m-%d %H:%M')} — {task_id} ({agent})\n")
        f.write(f"**Error:** {error}\n")
        f.write(f"**Action Required:** Manual data collection needed\n")

def run_agent(task_id: str, agent_name: str, script_path: str):
    print(f"\n{'='*60}")
    print(f"▶ Running {task_id}: {agent_name}")
    print(f"{'='*60}")
    try:
        result = subprocess.run(
            [sys.executable, script_path],
            capture_output=True, text=True, timeout=300
        )
        print(result.stdout)
        if result.returncode != 0:
            print(f"❌ {agent_name} failed:\n{result.stderr}")
            log_issue(task_id, agent_name, result.stderr[:500])
        else:
            print(f"✅ {task_id} completed successfully")
    except subprocess.TimeoutExpired:
        msg = "Agent timed out after 5 minutes"
        print(f"⏰ {msg}")
        log_issue(task_id, agent_name, msg)
    except Exception as e:
        print(f"❌ Exception: {e}")
        log_issue(task_id, agent_name, str(e))

def main():
    print("🤖 P1 Research Agent Orchestrator")
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Repo: https://github.com/SanKabira/P1-TInvIT-Bengaluru-RWA-Tokenization")
    
    # Initialize ISSUES.md
    if not os.path.exists(ISSUES_FILE):
        with open(ISSUES_FILE, 'w') as f:
            f.write("# 🚨 Data Collection Issues Log\n\n")
            f.write("Auto-generated by agent_orchestrator.py\n")
    
    for task_id, agent_name, script_path in AGENT_PIPELINE:
        if os.path.exists(script_path):
            run_agent(task_id, agent_name, script_path)
        else:
            print(f"⚠️ Script not found: {script_path}")
            log_issue(task_id, agent_name, f"Script file missing: {script_path}")
    
    print(f"\n✅ Orchestration complete: {datetime.now().strftime('%H:%M:%S')}")
    print("Check ISSUES.md for any data gaps.")

if __name__ == "__main__":
    main()
